### ISSUE TITLE
set-output deprecated

### ISSUE THREAD

**Issue by gopinath-velayudhan-mns** [DigitalInnovation/cloud-devsecops-pipelineactions#51]
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by GopikaV24** [comment]
https://github.com/DigitalInnovation/cloud-devsecops-pipelineactions/pull/109

DOne the changes
